update scripts

diff --git a/root/etc/cont-init.d/70-vpn-setup b/root/etc/cont-init.d/70-vpn-setup
--- a/root/etc/cont-init.d/70-vpn-setup
+++ b/root/etc/cont-init.d/70-vpn-setup
@@ -12,6 +12,31 @@ if [[ -z "$PROTONVPN_PASSWORD" ]]; then
   exit 3
 fi
 
+if [[ -z "$PROTONVPN_SERVER" ]] &&  [[ ! -z ${PROTONVPN_COUNTRY} ]]; then
+  echo "[VPN-Config-Setup] Using Fastest Server from ${PROTONVPN_COUNTRY}"
+elif [[ -z "$PROTONVPN_COUNTRY" ]] &&  [[ ! -z ${PROTONVPN_SERVER} ]]; then
+  echo "[VPN-Config-Setup] Using Server ${PROTONVPN_SERVER}"
+else
+  echo "[VPN-Config-Setup] Specify either PROTONVPN_SERVER(${PROTONVPN_SERVER}) or PROTONVPN_COUNTRY(${PROTONVPN_COUNTRY})"
+  exit 4
+fi
+
+case ${PROTONVPN_TIER} in
+  0 | free | Free | FREE)       echo "[VPN-Config-Setup] Free Plan";CFG_TIER=0;;
+  1 | basic | Basic | BASIC)    echo "[VPN-Config-Setup] Basic Plan";CFG_TIER=1;;
+  2 | plus | Plus | PLUS)       echo "[VPN-Config-Setup] Plus Plan";CFG_TIER=2;;
+  3 | visionary | Visionary | VISIONARY) echo "Yo Dwag! You have Visionary Plan!";PROTONVPN_TIER=3;;
+  *)                            echo "Invalid ProtonVPN Tier, Can only accept 0-3";exit 4;;
+esac
+
+case ${PROTONVPN_PROTOCOL} in
+  tcp | TCP)                    echo "[VPN-Config-Setup] UDP";CFG_PROTO="tcp";;
+  udp | UDP)                    echo "[VPN-Config-Setup] TCP";CFG_PROTO="udp";;
+  *)                            echo "[VPN-Config-Setup] Invalid Proto ${PROTONVPN_PROTOCOL}, Falling back to UDP";
+                                CFG_PROTO="udp";;
+esac
+
+
 IP_ADD_REGEX='([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
 SUBNET_REGEX='([0-9]|[12][0-9]|3[012])'
 
@@ -37,19 +62,17 @@ fi
 
 if [[ ${#INVALID_CIDRS[@]} -gt 0 ]];then
   echo "[VPN-Config-Split] Following CIDRs were invalid: ${INVALID_CIDRS[*]}"
-  exit 1
+  exit 5
 fi
-
 
 # Setup DNS leak protection
-if [[ ${PROTONVPN_DNS_LEAK_PROTECT} -eq 0 ]] || [[ ${PROTONVPN_DNS_LEAK_PROTECT} == "false" ]]; then
-  echo "[VPN-Config-DNS] Disabling DNS leak protection!!"
+if [[ ${PROTONVPN_DNS_LEAK_PROTECT} -eq 0 ]]; then
+  echo "[VPN-Config-DNS  ] Disabling DNS leak protection!!"
   DNS_LEAK_PROTECTION=0
 else
-  echo "[VPN-Config-DNS] Enabling DNS leak protection."
+  echo "[VPN-Config-DNS  ] Enabling DNS leak protection."
   DNS_LEAK_PROTECTION=1
 fi
-
 
 # Handle Split Tunnels
 if [[ ${#SPLIT_TUNNEL_CIDRS[@]} -gt 0 ]];then
@@ -60,45 +83,30 @@ else
   ENABLE_SPLIT_TUNNEL=0
 fi
 
-echo "[Path Init] Creating folders"
+echo "[Path Init       ] Creating folders"
 mkdir -p /root/.pvpn-cli/
 
 # permissions
-echo "[Path Init] Permissions"
+echo "[Path Init       ] Permissions"
 chown root:root /root/.pvpn-cli/
 
-case ${PROTONVPN_TIER} in
-  0 | free | Free | FREE)       echo "[VPN-Config-Setup] Free Plan";CFG_TIER=0;;
-  1 | basic | Basic | BASIC)    echo "[VPN-Config-Setup] Basic Plan";CFG_TIER=1;;
-  2 | plus | Plus | PLUS)       echo "[VPN-Config-Setup] Plus Plan";CFG_TIER=2;;
-  3 | visionary | Visionary | VISIONARY) echo "Yo Dwag! You have Visionary Plan!";PROTONVPN_TIER=3;;
-  *)                            echo "Invalid ProtonVPN Tier, Can only accept 0-3";exit 4;;
-esac
+# Pull Server Info
+echo "[VPN-Config-Setup] Getting Server List"
+curl --fail \
+    --location \
+    --silent \
+    --show-error \
+    --max-time 20 \
+    --silent \
+    --location \
+    --user-agent 'protonvpn-cli-docker' \
+    --header 'x-pm-appversion: LinuxVPN_2.2.6' \
+    --header 'x-pm-apiversion: 3' \
+    --header 'Accept: application/vnd.protonmail.v1+json' \
+    --output /root/.pvpn-cli/serverinfo.json \
+    https://api.protonvpn.ch/vpn/logicals
 
-case ${PROTONVPN_PROTOCOL} in
-  tcp | TCP)                    echo "[VPN-Config-Setup] UDP";CFG_PROTO="tcp";;
-  udp | UDP)                    echo "[VPN-Config-Setup] TCP";CFG_PROTO="udp";;
-  *)                            echo "[VPN-Config-Setup] Invalid Proto ${PROTONVPN_PROTOCOL}, Falling back to UDP";
-                                CFG_PROTO="udp";;
-esac
-
-# # Pull Server Info
-# echo "[VPN-Config-Setup] Getting Server List"
-# curl --fail \
-#     --location \
-#     --silent \
-#     --show-error \
-#     --max-time 20 \
-#     --silent \
-#     --location \
-#     --user-agent 'protonvpn-cli-docker' \
-#     --header 'x-pm-appversion: LinuxVPN_2.2.6' \
-#     --header 'x-pm-apiversion: 3' \
-#     --header 'Accept: application/vnd.protonmail.v1+json' \
-#     --output /root/.pvpn-cli/serverinfo.json \
-#     https://api.protonvpn.ch/vpn/logicals
-
-# __METADATA_PULL_DATE="$(date +%s)"
+__METADATA_PULL_DATE="$(date +%s)"
 
 echo "[VPN-Config-Setup] Writing config file"
 cat > /root/.pvpn-cli/pvpn-cli.cfg <<EOF
diff --git a/root/etc/services.d/protonvpn/run b/root/etc/services.d/protonvpn/run
--- a/root/etc/services.d/protonvpn/run
+++ b/root/etc/services.d/protonvpn/run
@@ -1,18 +1,24 @@
 #!/usr/bin/with-contenv bash
-# shellcheck shell=bash
+
+_term() {
+  echo "[Service Terminate] Caught SIGTERM signal!"
+  PVPN_DEBUG="${DEBUG:-0}" /usr/local/bin/protonvpn disconnect
+}
+
+trap _term SIGINT
+trap _term SIGTERM
 
 function connect_vpn()
 {
-  if [[ -z "$PROTONVPN_SERVER" ]]; then
+  if [[ -z "$PROTONVPN_SERVER" ]] &&  [[ -n ${PROTONVPN_COUNTRY} ]]; then
     echo "[Service Connect] Using Fastest Server from ${PROTONVPN_COUNTRY}"
-    PVPN_DEBUG="${DEBUG:-0}" /usr/local/bin/protonvpn c --cc "${PROTONVPN_COUNTRY:-NL}"
-  else
-    if [[ -z "${PROTONVPN_COUNTRY}" ]]; then
-      echo "ProtonVPN server is specified but country is empty!"
-      exit 4
-    fi
+    PVPN_DEBUG="${DEBUG:-0}" /usr/local/bin/protonvpn connect --cc "${PROTONVPN_COUNTRY}"
+  elif [[ -z "$PROTONVPN_COUNTRY" ]] &&  [[ -n ${PROTONVPN_SERVER} ]]; then
     echo "[Service Connect] Using Server ${PROTONVPN_SERVER}"
     PVPN_DEBUG="${DEBUG:-0}" /usr/local/bin/protonvpn connect "${PROTONVPN_SERVER}"
+  else
+    echo "[Service Error] Specify either PROTONVPN_SERVER(${PROTONVPN_SERVER}) or PROTONVPN_COUNTRY(${PROTONVPN_COUNTRY})"
+    exit 4
   fi
 }
 
@@ -36,11 +42,11 @@ function api_check()
     --max-time 20 \
     --silent \
     --location \
-    --user-agent 'protonvpn-cli-docker' \
-    --header 'x-pm-appversion: LinuxVPN_2.2.6' \
-    --header 'x-pm-apiversion: 3' \
-    --header 'Accept: application/vnd.protonmail.v1+json' \
-    https://api.protonvpn.ch/vpn/location | jq -r '.Country')"
+    https://ipinfo.io | jq -r '.country')"
+
+  if [[ -z ${PROTONVPN_COUNTRY} ]]; then
+    PROTONVPN_COUNTRY="$(python3 /usr/local/bin/proton-srv-country)"
+  fi
 
   if [[ $COUNTRY == "${PROTONVPN_COUNTRY}" ]]; then
     echo "[Service Check] OK!"
@@ -102,7 +108,8 @@ function main()
   while :
   do
     check_vpn
-    sleep "${LIVE_PROBE_INTERVAL}"
+    sleep "${LIVE_PROBE_INTERVAL}" &
+    wait $!
   done
 }
 
