custom dns servers

diff --git a/root/etc/cont-init.d/70-vpn-setup b/root/etc/cont-init.d/70-vpn-setup
--- a/root/etc/cont-init.d/70-vpn-setup
+++ b/root/etc/cont-init.d/70-vpn-setup
@@ -12,6 +12,77 @@ if [[ -z "$PROTONVPN_PASSWORD" ]]; then
   exit 3
 fi
 
+IP_ADD_REGEX='([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
+SUBNET_REGEX='([0-9]|[12][0-9]|3[012])'
+
+cidrs_from_env=(${PROTONVPN_EXCLUDE_CIDRS//,/ })
+
+declare -g -a SPLIT_TUNNEL_CIDRS INVALID_CIDRS DNS_SERVERS INVALID_DNS_SERVERS
+
+# Split Tunnels
+if [[ ${#cidrs_from_env[@]} -gt 0 ]]; then
+  echo "[VPN-Config-Split] Validating CIDRs"
+  for cidr in "${cidrs_from_env[@]}"; do
+    if [[ $cidr =~ ^$IP_ADD_REGEX(\.$IP_ADD_REGEX){3}/$SUBNET_REGEX$ ]]; then
+      echo "[VPN-Config-Split] CIDR $cidr is valid"
+      SPLIT_TUNNEL_CIDRS+=("$cidr")
+    else
+      echo "[VPN-Config-Split] CIDR $cidr is INVALID"
+      INVALID_CIDRS+=("$cidr")
+    fi
+  done
+else
+  echo "[VPN-Config-Split] No need to setup split Tunnels"
+fi
+
+if [[ ${#INVALID_CIDRS[@]} -gt 0 ]];then
+  echo "[VPN-Config-Split] Following CIDRs were invalid: ${INVALID_CIDRS[*]}"
+  exit 1
+fi
+
+# Custom DNS
+dns_servers=(${PROTONVPN_DNS_SERVERS//,/ })
+if [[ ${#dns_servers[@]} -eq 0 ]]; then
+  echo "[VPN-Config-DNS] Using ProtonVPN DNS"
+  echo "[VPN-Config-DNS] Enabling DNS leak protection"
+else
+  for dns in "${dns_servers[@]}"; do
+    if [[ $dns =~ ^$IP_ADD_REGEX(\.$IP_ADD_REGEX){3}$ ]]; then
+      echo "[VPN-Config-DNS] IP $dns is a valid IP"
+      DNS_SERVERS+=("$dns")
+    else
+      echo "[VPN-Config-DNS] IP $dns is an INVALID IP"
+      INVALID_DNS_SERVERS+=("$dns")
+    fi
+  done
+fi
+
+if [[ ${#INVALID_DNS_SERVERS[@]} -gt 0 ]];then
+  echo "[VPN-Config-DNS] Following DNS IPs were invalid: ${INVALID_DNS_SERVERS[*]}"
+  exit 1
+fi
+
+
+# Setup Custom DNS
+if [[ ${#DNS_SERVERS[@]} -gt 0 ]];then
+  echo "[VPN-Config-DNS] Using Custom DNS Servers ${DNS_SERVERS[*]}"
+  echo "[VPN-Config-DNS] Disabling DNS leak protection!"
+  DNS_LEAK_PROTECTION=0
+else
+  DNS_LEAK_PROTECTION=1
+  DNS_SERVERS=("None")
+fi
+
+
+# Handle Split Tunnels
+if [[ ${#SPLIT_TUNNEL_CIDRS[@]} -gt 0 ]];then
+  echo "[VPN-Config-Split] Following CIDRs will be excluded from VPN ${SPLIT_TUNNEL_CIDRS[*]}"
+  ENABLE_SPLIT_TUNNEL=1
+else
+  echo "[VPN-Config-Split] Disabled"
+  ENABLE_SPLIT_TUNNEL=0
+fi
+
 echo "[Path Init] Creating folders"
 mkdir -p /root/.pvpn-cli/
 
@@ -63,27 +134,20 @@ tier = ${CFG_TIER}
 default_protocol = ${CFG_PROTO}
 # Indicates that protonvpn init has been successful
 initialized = 1
-dns_leak_protection = 1
-custom_dns = None
+dns_leak_protection = ${DNS_LEAK_PROTECTION}
+custom_dns = ${DNS_SERVERS[*]}
 check_update_interval = 3
-killswitch = 0
-split_tunnel = 1
+killswitch = 1
+split_tunnel = ${ENABLE_SPLIT_TUNNEL}
 
 [metadata]
 last_api_pull = ${__METADATA_PULL_DATE}
 last_update_check = 0
 EOF
 
-if [[ ! -f /root/.pvpn-cli/split_tunnel.txt  ]]; then
+if [[ ${ENABLE_SPLIT_TUNNEL} -eq 1 ]];then
   echo "[VPN-Config-Setup] Writing Split Tunnel Config file"
-  cat > /root/.pvpn-cli/split_tunnel.txt <<EOF
-192.168.0.0/16
-172.16.0.0/12
-10.0.0.0/8
-169.254.0.0/16
-EOF
-else
-  echo "[VPN-Config-Setup] Respecting existing split tunnel config"
+  printf "%s\n" "${SPLIT_TUNNEL_CIDRS[@]}" > /root/.pvpn-cli/split_tunnel.txt
 fi
 
 echo "[VPN-Config-Setup] Writing credentials file"
