feat: Merge `PROTONVPN_SERVER` and `PROTONVPN_COUNTRY` into `PROTONVPN_SERVER`.
BREAKING CHANGES:

- Specifying `PROTONVPN_SERVER` is now required environment variable.
- `PROTONVPN_COUNTRY` is merged into `PROTONVPN_SERVER`.
- Users who are migrating from version 4.x or below rename `PROTONVPN_COUNTRY` to `PROTONVPN_SERVER`.
- You can migrate value of `PROTONVPN_COUNTRY` to `PROTONVPN_SERVER`. Container will detect that you wish to connct to country specified and connect as usual.

diff --git a/root/etc/cont-init.d/70-vpn-setup b/root/etc/cont-init.d/70-vpn-setup
--- a/root/etc/cont-init.d/70-vpn-setup
+++ b/root/etc/cont-init.d/70-vpn-setup
@@ -2,40 +2,94 @@
 # shellcheck shell=bash
 set -eo pipefail
 
+export LOG_FMT="full"
+if [[ $DEBUG == "1" ]]; then
+  export LOG_LVL=0
+fi
+
+if [[ -f /usr/local/lib/loggers/logger.sh ]]; then
+  # shellcheck disable=SC1091
+  source /usr/local/lib/loggers/logger.sh
+else
+  echo "[ERROR ] Failed to loag logging library at/usr/local/lib/loggers/logger.sh"
+  exit 1
+fi
+
 if [[ -z "$PROTONVPN_USERNAME" ]]; then
-  echo "No Username specified!"
+  log_error "No Username specified!"
   exit 2
 fi
 
 if [[ -z "$PROTONVPN_PASSWORD" ]]; then
-  echo "No Password specified!"
+  log_error "No Password specified!"
   exit 3
 fi
 
-if [[ -z "$PROTONVPN_SERVER" ]] &&  [[ -n ${PROTONVPN_COUNTRY} ]]; then
-  echo "[VPN-Config-Setup] Using Fastest Server from ${PROTONVPN_COUNTRY}"
-elif [[ -z "$PROTONVPN_COUNTRY" ]] &&  [[ -n ${PROTONVPN_SERVER} ]]; then
-  echo "[VPN-Config-Setup] Using Server ${PROTONVPN_SERVER}"
+if [[ -z ${PROTONVPN_CHECK_URL} ]]; then
+  log_error "Healthcheck endpoint not defined!"
+  exit 3
+fi
+
+if [[ ${PROTONVPN_CHECK_URL} =~ ^https://* ]]; then
+    log_success "OK! Check URL is secure"
 else
-  echo "[VPN-Config-Setup] Specify either PROTONVPN_SERVER(${PROTONVPN_SERVER}) or PROTONVPN_COUNTRY(${PROTONVPN_COUNTRY})"
-  exit 4
+    log_error "PROTONVPN_CHECK_URL must be secure(https)"
+    exit 3
+fi
+# Validate healthcheck endpoint returns 200
+if [[ $(curl -s -o /dev/null -w "%{http_code}" "${PROTONVPN_CHECK_URL}") == "200" ]]; then
+  log_success "Healthcheck endpoint returned 200"
+else
+  log_error "Your PROTONVPN_CHECK_URL: ${PROTONVPN_CHECK_URL} is invalid or is not responding with 200"
+  exit 3
+fi
+
+# Validate healthcheck query returns non empty
+init_check_resp="$(curl -s "${PROTONVPN_CHECK_URL}" | jq -r "${PROTONVPN_CHECK_QUERY}")"
+if [[ $init_check_resp =~ ^[a-zA-Z]{2}$ ]]; then
+  log_success "Healthcheck endpoint query returned: ${init_check_resp}"
+else
+  log_error "Your PROTONVPN_CHECK_URL or PROTONVPN_CHECK_QUERY is invalid (${init_check_resp})"
+  exit 3
 fi
 
 case ${PROTONVPN_TIER} in
-  0 | free | Free | FREE)                echo "[VPN-Config-Setup] Free Plan";CFG_TIER=0;;
-  1 | basic | Basic | BASIC)             echo "[VPN-Config-Setup] Basic Plan";CFG_TIER=1;;
-  2 | plus | Plus | PLUS)                echo "[VPN-Config-Setup] Plus Plan";CFG_TIER=2;;
-  3 | visionary | Visionary | VISIONARY) echo "[VPN-Config-Setup] Visionary Plan";CFG_TIER=3;;
-  *)                                     echo "Invalid ProtonVPN Tier, Can only accept 0-3";exit 4;;
+  0 | free | Free | FREE)                log_notice "Free Plan";CFG_TIER=0;;
+  1 | basic | Basic | BASIC)             log_notice "Basic Plan";CFG_TIER=1;;
+  2 | plus | Plus | PLUS)                log_notice "Plus Plan";CFG_TIER=2;;
+  3 | visionary | Visionary | VISIONARY) log_notice "Visionary Plan";CFG_TIER=3;;
+  *)                                     log_error "Invalid ProtonVPN Tier, Can only accept 0-3";exit 3;;
 esac
 
 case ${PROTONVPN_PROTOCOL} in
-  tcp | TCP)                    echo "[VPN-Config-Setup] TCP";CFG_PROTO="tcp";;
-  udp | UDP)                    echo "[VPN-Config-Setup] UDP";CFG_PROTO="udp";;
-  *)                            echo "[VPN-Config-Setup] Invalid Proto ${PROTONVPN_PROTOCOL}, Falling back to UDP";
+  tcp | TCP)                    log_notice "Protocol: TCP";CFG_PROTO="tcp";;
+  udp | UDP)                    log_notice "Protocol: UDP";CFG_PROTO="udp";;
+  *)                            log_warning "Protocol: Invalid protocol specified - ${PROTONVPN_PROTOCOL}";
+                                log_warning "Falling back to UDP";
                                 CFG_PROTO="udp";;
 esac
 
+log_variable "PROTONVPN_SERVER"
+
+if [[ -z ${PROTONVPN_SERVER} ]]; then
+  log_error "Specify PROTONVPN_SERVER(${PROTONVPN_SERVER})"
+  exit 4
+fi
+
+if [[ ${PROTONVPN_SERVER^^} =~ ^[A-Z]{2}$ ]]; then
+  log_notice "Using fastest server from COUNTRY: ${PROTONVPN_COUNTRY^^}"
+elif [[ ${PROTONVPN_SERVER} == "RANDOM" ]]; then
+  log_notice "Using a RANDOM server"
+elif [[ ${PROTONVPN_SERVER} == "P2P" ]]; then
+  if [[ ${CFG_TIER} -lt 1 ]]; then
+    log_error "Using P2P requires basic plan or above!"
+    exit 4
+  else
+    log_notice "Using fastest available P2P server"
+  fi
+else
+  log_notice "Connecting to server: ${PROTONVPN_SERVER}"
+fi
 
 IP_ADD_REGEX='([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
 SUBNET_REGEX='([0-9]|[12][0-9]|3[012])'
@@ -47,52 +101,53 @@ declare -g -a SPLIT_TUNNEL_CIDRS INVALID_CIDRS
 
 # Split Tunnels
 if [[ ${#cidrs_from_env[@]} -gt 0 ]]; then
-  echo "[VPN-Config-Split] Validating CIDRs"
+  log_info "Validating CIDRs"
   for cidr in "${cidrs_from_env[@]}"; do
     if [[ $cidr =~ ^$IP_ADD_REGEX(\.$IP_ADD_REGEX){3}/$SUBNET_REGEX$ ]]; then
-      echo "[VPN-Config-Split] CIDR $cidr is valid"
+      log_info "CIDR $cidr is valid"
       SPLIT_TUNNEL_CIDRS+=("$cidr")
     else
-      echo "[VPN-Config-Split] CIDR $cidr is INVALID"
+      log_error "CIDR $cidr is INVALID"
       INVALID_CIDRS+=("$cidr")
     fi
   done
 else
-  echo "[VPN-Config-Split] No need to setup split Tunnels"
+  log_debug "Split tunnel is disabled!(${cidrs_from_env[*]})"
 fi
 
 if [[ ${#INVALID_CIDRS[@]} -gt 0 ]];then
-  echo "[VPN-Config-Split] Following CIDRs were invalid: ${INVALID_CIDRS[*]}"
+  log_error "Following CIDRs were invalid: ${INVALID_CIDRS[*]}"
   exit 5
 fi
 
 # Setup DNS leak protection
 if [[ ${PROTONVPN_DNS_LEAK_PROTECT} -eq 0 ]]; then
-  echo "[VPN-Config-DNS  ] Disabling DNS leak protection!!"
+  log_notice "Disabling DNS leak protection!!"
   DNS_LEAK_PROTECTION=0
 else
-  echo "[VPN-Config-DNS  ] Enabling DNS leak protection."
+  log_info "Enabling DNS leak protection."
   DNS_LEAK_PROTECTION=1
 fi
 
 # Handle Split Tunnels
 if [[ ${#SPLIT_TUNNEL_CIDRS[@]} -gt 0 ]];then
-  echo "[VPN-Config-Split] Following CIDRs will be excluded from VPN ${SPLIT_TUNNEL_CIDRS[*]}"
+  log_notice "Following CIDRs will be excluded from VPN ${SPLIT_TUNNEL_CIDRS[*]}"
   ENABLE_SPLIT_TUNNEL=1
 else
-  echo "[VPN-Config-Split] Disabled"
+  log_notice "Split tunneing is disabled"
+  log_warning "If your app container is running as as server, you may not be able to connect to it from external hosts!"
   ENABLE_SPLIT_TUNNEL=0
 fi
 
-echo "[Path Init       ] Creating folders"
+log_info "Creating folders"
 mkdir -p /root/.pvpn-cli/
 
 # permissions
-echo "[Path Init       ] Permissions"
+log_info "Set file permissions"
 chown root:root /root/.pvpn-cli/
 
 # Pull Server Info
-echo "[VPN-Config-Setup] Getting Server List"
+log_info "Prefetch server list"
 curl --fail \
     --location \
     --silent \
@@ -109,7 +164,7 @@ curl --fail \
 
 __METADATA_PULL_DATE="$(date +%s)"
 
-echo "[VPN-Config-Setup] Writing config file"
+log_info "Generating config file"
 cat > /root/.pvpn-cli/pvpn-cli.cfg <<EOF
 [USER]
 # API endpoint
@@ -132,16 +187,16 @@ last_update_check = 0
 EOF
 
 if [[ ${ENABLE_SPLIT_TUNNEL} -eq 1 ]];then
-  echo "[VPN-Config-Setup] Writing Split Tunnel Config file"
+  log_info "Generate split-tunnel config file"
   printf "%s\n" "${SPLIT_TUNNEL_CIDRS[@]}" > /root/.pvpn-cli/split_tunnel.txt
 fi
 
-echo "[VPN-Config-Setup] Writing credentials file"
+log_info "Writing credentials file"
 # https://github.com/ProtonVPN/linux-cli/blob/089af8d309cf774adc31c158a62a27733ae39ee0/protonvpn_cli/utils.py#L530
 cat > /root/.pvpn-cli/pvpnpass <<EOF
 ${PROTONVPN_USERNAME}+plc
 ${PROTONVPN_PASSWORD}
 EOF
 
-echo "[VPN-Config-Setup] Restrict credentials file"
+log_info "Restrict credentials file"
 chmod 600 /root/.pvpn-cli/pvpn-cli.cfg
diff --git a/root/etc/services.d/protonvpn/run b/root/etc/services.d/protonvpn/run
--- a/root/etc/services.d/protonvpn/run
+++ b/root/etc/services.d/protonvpn/run
@@ -1,58 +1,77 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
+export LOG_FMT="full"
+if [[ $DEBUG == "1" ]]; then
+  export LOG_LVL=0
+fi
+
+if [[ -f /usr/local/lib/loggers/logger.bash ]]; then
+  # shellcheck disable=SC1091
+  source /usr/local/lib/loggers/logger.bash
+else
+  echo "[ERROR ] Failed to loag logging library at/usr/local/lib/loggers/logger.bash"
+  exit 1
+fi
+
+
 # Reset disconnect mode flag
 PROTONVPN_SVC_DISCONNECTING=0
 
 _term() {
-  echo "[Service Terminate] Caught SIGTERM signal!"
+  log_info "Caught SIGTERM signal!"
   # Dont reconnect if already in term mode
   PROTONVPN_SVC_DISCONNECTING=1
-  echo "[Service Terminate] Disconnecting!"
+  log_info "Disconnecting!"
   if PVPN_DEBUG="${DEBUG:-0}" protonvpn disconnect; then
-    echo "[Service Terminate] Diconnected"
+    log_success "Diconnected"
   else
-    echo "[Service Terminate] Failed"
+    log_error "Failed to disconnect!"
   fi
 }
 
 trap _term SIGTERM SIGINT
 
-readonly SVC_INIT="[Service - INIT]"
-readonly SVC_CONN="[Service - CONN]"
-readonly SVC_RCON="[Service - RCON]"
-readonly SVC_CHCK="[Service - CHCK]"
-
-
 function connect_vpn()
 {
-  if [[ -z $PROTONVPN_SERVER ]] && [[ -n ${PROTONVPN_COUNTRY} ]]; then
-    echo "${SVC_CONN} Using Fastest Server from ${PROTONVPN_COUNTRY}"
-    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --cc "${PROTONVPN_COUNTRY}"
-  elif [[ ${PROTONVPN_SERVER} == "RANDOM" ]] && [[ -z ${PROTONVPN_COUNTRY} ]]; then
-    echo "${SVC_CONN} Using Random Server"
-    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --random
-  elif [[ ${PROTONVPN_SERVER} == "P2P" ]] && [[ -z ${PROTONVPN_COUNTRY} ]]; then
-    echo "${SVC_CONN} Using Fastest P2P Server"
-    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --p2p
-  elif [[ -z $PROTONVPN_COUNTRY ]] && [[ -n ${PROTONVPN_SERVER} ]]; then
-    echo "${SVC_CONN} Using Server ${PROTONVPN_SERVER}"
-    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect "${PROTONVPN_SERVER}"
-  else
-    echo "${SVC_CONN} Specify either PROTONVPN_SERVER(${PROTONVPN_SERVER}) or PROTONVPN_COUNTRY(${PROTONVPN_COUNTRY})"
+
+  if [[ -z ${PROTONVPN_SERVER} ]]; then
+    log_error "Specify PROTONVPN_SERVER(${PROTONVPN_SERVER})"
     exit 4
+  fi
+
+  if [[ ${PROTONVPN_SERVER^^} =~ ^[A-Z]{2}$ ]]; then
+    log_notice "Using fastest server from COUNTRY: ${PROTONVPN_SERVER^^}"
+    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --cc "${PROTONVPN_SERVER^^}"
+
+  elif [[ ${PROTONVPN_SERVER} == "RANDOM" ]]; then
+    log_notice "Using a RANDOM server"
+    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --random
+
+  elif [[ ${PROTONVPN_SERVER} == "P2P" ]]; then
+    if [[ ${CFG_TIER} -lt 1 ]]; then
+      log_error "Using P2P requires basic plan or above!"
+      exit 4
+    else
+      log_notice "Using fastest available P2P server"
+      PVPN_DEBUG="${DEBUG:-0}" protonvpn connect --p2p
+    fi
+
+  else
+    log_notice "Connecting to server: ${PROTONVPN_SERVER}"
+    PVPN_DEBUG="${DEBUG:-0}" protonvpn connect "${PROTONVPN_SERVER}"
   fi
 }
 
 
 function reconnect_vpn()
 {
-  echo "${SVC_RCON} Attempting..."
+  log_warning "Reconnecting..."
   if PVPN_DEBUG="${DEBUG:-0}" protonvpn r; then
-    echo "${SVC_RCON} Successful"
+    log_success "Reconnection successful"
   else
-    echo "${SVC_RCON} Failure!"
-    echo "${SVC_RCON} Trying with a fresh connection!"
+    log_error "Failed to reconnect"
+    log_warning "Trying with a fresh connection!"
     connect_vpn
   fi
 }
@@ -64,20 +83,18 @@ function api_check()
     --max-time 20 \
     --silent \
     --location \
-    https://ipinfo.io | jq -r '.country')"
+    "${PROTONVPN_CHECK_URL}" | jq -r "${PROTONVPN_CHECK_QUERY}")"
 
-  if [[ -z ${PROTONVPN_COUNTRY} ]]; then
-    PROTONVPN_COUNTRY="$(python3 /usr/local/bin/proton-srv-country)"
-  fi
+  PROTONVPN_COUNTRY="$(python3 /usr/local/bin/proton-srv-country)"
 
   if [[ $COUNTRY == "${PROTONVPN_COUNTRY}" ]]; then
-    echo "${SVC_CHCK} OK!"
+    log_success "Healthchecks passed"
     thrshold_f=0
   else
-    echo "${SVC_CHCK} #$(( ++thrshold_f )) Failed!"
-    echo "${SVC_CHCK} connected to #${COUNTRY} instead of #${PROTONVPN_COUNTRY}"
+    log_error "Healthcheck #$(( ++thrshold_f )) Failed!"
+    log_error "Connected to #${COUNTRY} instead of #${PROTONVPN_COUNTRY}"
     if [[ $thrshold_f -gt "${PROTONVPN_FAIL_THRESHOLD}" ]];then
-      echo "${SVC_CHCK} failed > allowed times(${PROTONVPN_FAIL_THRESHOLD}), reconnecting!"
+      log_error "Reconnecting! (${PROTONVPN_FAIL_THRESHOLD})"
       reconnect_vpn
     fi
   fi
@@ -88,13 +105,13 @@ function check_vpn()
   # Check if openvpnv process is running.
   if [[ ${PROTONVPN_SVC_DISCONNECTING} -ne 1 ]]; then
     if [[ -z "$(pgrep -x openvpn)" ]]; then
-      echo "${SVC_CHCK} Error!! There is no OpenVPN Process!!"
+      log_error "There is no OpenVPN Process!!"
       reconnect_vpn
     else
       api_check
     fi
   else
-    echo "${SVC_CHCK} Skipped checks beacuse we are terminating"
+    log_debug "Skipped checks beacuse container is terminating"
   fi
 }
 
@@ -104,27 +121,27 @@ function main()
 
   re='^[0-9]+$'
   if ! [[ $PROTONVPN_CHECK_INTERVAL =~ $re ]] ; then
-    echo "${SVC_INIT} PROTONVPN_CHECK_INTERVAL can only be an integer!, will default to 60 seconds"
-    PROTONVPN_CHECK_INTERVAL=60
+    log_warning "PROTONVPN_CHECK_INTERVAL can only be an integer!, will default to 90 seconds"
+    PROTONVPN_CHECK_INTERVAL=90
   else
-    echo "${SVC_INIT} Daemon check interval is set to #$PROTONVPN_CHECK_INTERVAL"
+    log_info "PROTONVPN_CHECK_INTERVAL is set to #$PROTONVPN_CHECK_INTERVAL"
   fi
 
   if ! [[ $PROTONVPN_FAIL_THRESHOLD =~ $re ]] ; then
-    echo "${SVC_INIT} PROTONVPN_FAIL_THRESHOLD can only be an integer!, will default to 3"
+    log_warning "PROTONVPN_FAIL_THRESHOLD can only be an integer!, will default to 3"
     PROTONVPN_FAIL_THRESHOLD=3
   else
-    echo "${SVC_INIT} Reconnect treshold is #$PROTONVPN_FAIL_THRESHOLD"
+    log_info "Reconnect treshold is #$PROTONVPN_FAIL_THRESHOLD"
   fi
 
-  echo "${SVC_INIT} checking orphaned openvpn process"
+  log_info "Checking orphaned openvpn process"
   OVPN_PROCESS="$(pgrep -x openvpn)"
   if [[ -z ${OVPN_PROCESS} ]]; then
-    echo "${SVC_INIT} This appears to be a fresh start!"
+    log_info "This appears to be a fresh start!"
     thrshold_f=0
     connect_vpn
   else
-    echo "${SVC_INIT} This appears to be a restart!, reconnecting to VPN with old settings"
+    log_info "This appears to be a restart!, reconnecting with old settings"
     thrshold_f=0
     reconnect_vpn
   fi
@@ -132,7 +149,7 @@ function main()
   # Checks
   while :
   do
-    echo "${SVC_CHCK} Is Service Disconnecting: ${PROTONVPN_SVC_DISCONNECTING}"
+    log_debug "Is service disconnecting: ${PROTONVPN_SVC_DISCONNECTING}"
     check_vpn
     sleep "${PROTONVPN_CHECK_INTERVAL}" &
     wait $!
